server:
  port: 8081

logging:
  level:
    org.springframework.web: error
    com.ssafy: debug
    org.hibernate.SQL: debug
  pattern:
    console: "%d{HH:mm:ss} %clr(%5p) [%c] %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    
spring:
  datasource:
    url: jdbc:mysql://k02a1011.p.ssafy.io/g_money_full?autoReconnect=true
    username: root
    password: ssafytest
    initialization-mode: never
    sql-script-encoding: UTF-8
    continue-on-error: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
jwt:
  secret: 1q2w3e4r!@
  